name: Run Python Program
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted # This targets any self-hosted runner

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        eval "$(conda shell.bash hook)"
        echo "source ~/opt/anaconda3/etc/profile.d/conda.sh" >> $GITHUB_ENV
        conda info
        conda env list
        echo $SHELL
        echo $PATH
        conda activate mlflow 
      shell: bash 
    - name: Run Python program
      run: python train.py
