name: Run Python Program
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted # This targets any self-hosted runner

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        conda activate mlflow
    - name: Run Python program
      run: python train.py
