name: Run Python Program
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted # This targets any self-hosted runner

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name : brew update
      run : |
        brew upgrade 
        brew update
    - name: Install dependencies
      run: |
        
        brew upgrade
        pip install -r requirements.txt
    - name: Run Python program
      run: python train.py
