name: Run Python Program

on:
  workflow_dispatch:
    inputs:
      Experiment:
        description: 'Log level'     
        required: true
        default: 'Experiment1'
      Alpha:
        description: 'Hyper Parameter'     
        required: true
        default: '0.5'
      l1:
        description: 'Hyper Parameter'     
        required: true
        default: '0.5'
jobs:
  build:
    runs-on: self-hosted # This targets any self-hosted runner

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        eval "$(conda shell.bash hook)"
        conda activate mlflow 
        pip uninstall pandas -y
        pip uninstall numpy -y
        pip install pandas
        pip install numpy
        conda info
        python train.py ${{ inputs.Experiment }} ${{ inputs.Alpha }} ${{ inputs.l1 }}
      shell: bash 
