name: Run Python Program

on:
  workflow_dispatch:
    inputs:
      Experiment:
        description: 'Experiment Name'     
        required: true
        default: 'Experiment-mlops'
      Alpha:
        description: 'Hyper Parameter Alpha'     
        required: true
        default: '0.5'
      l1:
        description: 'Hyper Parameter L1 ratio'     
        required: true
        default: '0.5'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python environment and run train.py with parameters
      run: |
        eval "$(conda shell.bash hook)"
        conda activate mlflow-latest
        conda info
        python train.py "${{ github.event.inputs.Experiment }}" "${{ github.event.inputs.Alpha }}" "${{ github.event.inputs.l1 }}"
      shell: bash
