name: Run Python Program
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted # This targets any self-hosted runner

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        eval "$(conda shell.bash hook)"
        conda activate mlflow 
        pip uninstall pandas -y
        pip uninstall numpy -y
        pip install pandas
        pip install numpy
        conda info
        python train.py
      shell: bash 
