name: Run Python Program
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted # This targets any self-hosted runner

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        eval "$(conda shell.bash hook)"
        conda activate mlflow 
        python3 -m pip uninstall numpy
        python3 -m pip install numpy==1.14.0
        conda info
      shell: bash 
    - name: Run Python program
      run: python train.py
